global:
  excluded_paths:
    - '**/*shop.ts'
    - './**/*.spec.ts' # mocha tests
    - './**/*.spec.js'
    - './**/*.int.js' # jest tests
    - '**/*.unit.js'
    - './**/*.int.ts'
    - './**/*.unit.ts'
    - 'sensitive/**'

sast:
   excluded_paths:
      - './**/*.unit.js'
