global:
  excluded_paths:
    - './**/*.spec.ts' # mocha tests
    - './**/*.spec.js'
    - './**/*.int.js' # jest tests
    - './**/*.unit.js'
    - './**/*.int.ts'
    - './**/*.unit.ts'

sast:
   excluded_paths:
      - './**/*.unit.js'
